Update View+Extension
YusukeHosonuma/SwiftUI-Common pull request #38
Opened 2022-06-04 10:09 UTC by bamboo-wood

## View+Extensionにレイアウトに関する関数を実装しました。
 @YusukeHosonuma  
初めまして、TwitterでのiOS/SwiftUIに関する情報発信にいつも感謝しております。
私がSwiftUIの開発で普段使っているものをご提案させていただければかと思います。
（といっても、いつもチェックしている海外サイトのコピーコードなのですが。）

## 引用元
[https://kavsoft.dev/](https://kavsoft.dev/)

2022-06-04 22:52 UTC, YusukeHosonuma requested changes
PR ありがとうございます！

以前からこれ系の API を追加しようか迷っていたので、追加する判断ができました 🙏 
（私のは View + `Spacer` ベースの実装でしたが）

2点コメントさせていただいたので、ご確認お願いしますー

2022-06-04 22:52 UTC, YusukeHosonuma commented on Sources/SwiftUICommon/Extension/View+.swift
> +
以下のような感じで、引用元の個別記事URLをコメントで追加してくださると嬉しいです！
https://github.com/YusukeHosonuma/SwiftUI-Common/blob/8ca1c43fda94037226241c86383bb6422013dd46/Sources/SwiftUICommon/Extension/View%2BLayer.swift#L37-L38

* 情報提供者への感謝
* API を利用する際の参考情報として活用（場合によっては妥当性検証）

の2点の理由からですー！

2022-06-04 22:52 UTC, YusukeHosonuma commented on Sources/SwiftUICommon/Extension/View+.swift
> +        self.frame(maxWidth: .infinity, alignment: .leading)
`make format` で SwiftFormat を実行してくださると少し助かります 🙏 

README に Development のセクションを追加しておきました↓
https://github.com/YusukeHosonuma/SwiftUI-Common#development

ちなみに忘れていても、どこかのタイミングで私が実行することになるので、特に問題はないです（笑）

2022-06-04 22:54 UTC, YusukeHosonuma commented
あ、あと Example プロジェクトに使い方が分かるコードを追加頂けるとありがたいです 🙏 （別 PR ＋余力あればで大丈夫です
https://github.com/YusukeHosonuma/SwiftUI-Common/blob/main/Example/Shared/ContentView.swift

2022-06-05 04:26 UTC, bamboo-wood commented
引用元のURLの記載と`make format`実行しました！

2022-06-05 05:56 UTC, YusukeHosonuma approved these changes

2022-06-05 05:56 UTC, YusukeHosonuma commented
早速の対応ありがとうございます！　マージさせていただきますー

2022-06-05 06:08 UTC, merged